### ISSUE TITLE
Nav bar & Footer changes

### ISSUE THREAD

**Issue by piasoy** [prphntm63/geneaology-website#6]
- [ ] correct the spelling of `Genealogy` (remove the letter `o` after  `a`) wherever applicable 

- [ ] replace `Genealogy` with the  company name `Aurora` (after one of the godmothers of Sleeping Beauty)

**Comment by prphntm63** [comment]
Everywhere besides the repo name, right? 🤣

**Comment by prphntm63** [comment]
Issues addressed in branch matt-bug-fixes

Added `Aurora` to class navbar-brand in /about, /services, and index pages to replace Geneology

Replaced brand in footer from Geneaology-Website to Aurora Services, Inc.

Replaced spelling of 'Geneology' in /about and /services
